spring.application.name=Atom_Backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/atom_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${SERVER_PORT:8080}

springdoc.swagger-ui.path=/swagger-ui.html

application.security.jwt.secret-key=${JWT_SECRET_KEY:change-me-change-me-change-me-change-me-123456}
application.security.jwt.expiration=${JWT_EXPIRATION:86400000}

application.integration.n8n.webhook-url=${N8N_WEBHOOK_URL:}